In [1]:
import numpy as np

In [8]:
A = np.random.rand(3, 4)
B = np.random.rand(4, 5)
print(A.shape, B.shape)

print(np.matmul(A, B))
print(np.einsum("ij,jk -> ik", A,B))

(3, 4) (4, 5)
[[1.06155502 0.82150936 0.91462684 1.18097623 0.1068072 ]
 [1.07581035 0.95634551 1.60615965 1.12614583 0.73567523]
 [1.16936758 0.82972152 1.17408322 1.0306906  0.50852197]]
[[1.06155502 0.82150936 0.91462684 1.18097623 0.1068072 ]
 [1.07581035 0.95634551 1.60615965 1.12614583 0.73567523]
 [1.16936758 0.82972152 1.17408322 1.0306906  0.50852197]]


In [10]:
A = np.random.rand(3, 4)
B = np.random.rand(3, 4)
print(A*B)
print(np.einsum('ij,ij -> ij', A, B))

[[0.32111806 0.2357027  0.16530526 0.31813075]
 [0.00302694 0.01525022 0.07906909 0.0020372 ]
 [0.42592921 0.07657249 0.64472758 0.16445191]]
[[0.32111806 0.2357027  0.16530526 0.31813075]
 [0.00302694 0.01525022 0.07906909 0.0020372 ]
 [0.42592921 0.07657249 0.64472758 0.16445191]]


In [11]:
np.einsum('ij -> ji', A)

array([[0.32289053, 0.12361542, 0.62560344],
       [0.62588531, 0.42235957, 0.08418457],
       [0.17408382, 0.7039036 , 0.67724216],
       [0.35454406, 0.00875995, 0.20795944]])

In [17]:
A = np.random.randint(0, 10, (2, 3, 4))
B = np.random.randint(0, 10, (2, 4, 5))
print(np.einsum('bij,bjk -> bik', A, B))

[[[ 88  37  32  59  64]
  [109  41  46  67  17]
  [125  59  70  73  65]]

 [[ 58  65  14  91 105]
  [ 63  65  55  74 100]
  [ 83 112  54 128 151]]]


In [20]:
A = np.random.randint(0, 10, (2, 3, 4))
print(A)
print()
print(np.sum(A))
print(np.einsum('bij ->', A))


[[[0 6 3 4]
  [7 3 6 3]
  [1 5 0 3]]

 [[1 0 9 9]
  [2 3 1 6]
  [5 2 8 8]]]

95
95


In [23]:
A = np.random.randint(0, 10, (3, 4))
print(A)
print(np.sum(A, axis=1))
print(np.einsum('ij -> i', A))

[[3 3 3 2]
 [7 9 2 7]
 [9 8 6 7]]
[11 25 30]
[11 25 30]


In [24]:
Q = np.random.randn(32, 64, 512)
k = np.random.randn(32, 128, 512)
print(np.einsum('bqm,bkm -> bqk', Q, k).shape)

(32, 64, 128)


In [25]:
A = np.random.randn(2, 4, 4, 2)
B = np.random.randn(2, 4, 4, 1)
print(np.einsum('bcik,bcij -> bckj', B, A).shape)

(2, 4, 1, 2)
