In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [4]:
tensor_str = tf.constant('hello world')
print(tensor_str)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [5]:
tensor_one_d = tf.constant([2, 0., -3], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int16)


In [6]:
tensor_two_d = tf.constant([
    [1,2,0], 
    [2,3,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 2  3 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [7]:
print(tensor_two_d.ndim)

2


In [8]:
import numpy as np

In [9]:
np_array = np.array([1, 2, 4])
print(np_array)

[1 2 4]


In [10]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [11]:
eye_tensor = tf.eye(5, batch_shape=[2, 4])
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [12]:
fill_tensor = tf.fill([3,4], 5)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [13]:
ones_tensor = tf.ones([5,3,2])
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [14]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [15]:
print(tf.shape(tensor_two_d))

tf.Tensor([4 3], shape=(2,), dtype=int32)


In [16]:
t = tf.constant([[1,1,1], [2,2,2]])
print(tf.size(t, out_type=tf.float32))

tf.Tensor(6.0, shape=(), dtype=float32)


In [17]:
randov_tensor = tf.random.normal(
    [3,2],
    mean=100.0
)
print(randov_tensor)

tf.Tensor(
[[ 99.50815   99.789116]
 [100.706345 100.78551 ]
 [ 98.817856  99.59441 ]], shape=(3, 2), dtype=float32)


In [18]:
random_tensor = tf.random.uniform([3,5], maxval=1000, dtype=tf.int32)
print(random_tensor)

tf.Tensor(
[[589 914 982 145 158]
 [985 853 680 235 726]
 [475 208  18 891 307]], shape=(3, 5), dtype=int32)


In [19]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[:4])
print(tensor_indexed[1:-1:2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)


In [20]:
tf.range(2,5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [21]:
tensor_two_d = tf.constant([
    [1,2,0], 
    [2,3,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d[..., 1])

tf.Tensor([2 3 5 3], shape=(4,), dtype=int32)


In [22]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [23]:
x_abs_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [24]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [25]:
x_1 = tf.constant([[5,3,6,6,4,6],], dtype=tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype=tf.float32)
print(x_1.shape, x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6) (3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [26]:
x_argmax = tf.constant([[2, 20, 30, 3, 6], 
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
print(x_argmax.shape)
print(tf.math.argmin(x_argmax, 1))

(3, 5)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [27]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [28]:
tensor_two_d = tf.constant([
    [1,2,0], 
    [2,3,-1],
    [1,5,6],
    [2,3,8]], dtype=tf.float16
)

print(tf.math.reduce_mean(tensor_two_d, axis=0))

tf.Tensor([1.5  3.25 3.25], shape=(3,), dtype=float16)


In [29]:
tf.math.top_k(tensor_two_d)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [3.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]])>)

In [30]:
x_1 = tf.constant([[1,2,0],
                   [3,5,-1]])
x_2 = tf.constant([[1,2,0],
                   [3,5,-1],
                   [4,5,6]])
print(x_1.shape, x_2.shape)
tf.linalg.matmul(x_1, x_2)

(2, 3) (3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]])>

In [31]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]])>

In [32]:
x_1 = tf.constant([[[1, 2],
                    [3, -1]],
                    [[2, 0],
                     [1, 2]],
                    [[5, 0],
                     [2, 0]]])
x_2 = tf.constant([[[5, 2, 4],
                    [3, 1, -10]],
                    [[1, 23, 0],
                     [1, 70, 2]],
                    [[5, 18, 0],
                     [2, 7, 90]]])
print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[[ 11   4 -16]
  [ 12   5  22]]

 [[  2  46   0]
  [  3 163   4]]

 [[ 25  90   0]
  [ 10  36   0]]], shape=(3, 2, 3), dtype=int32)


In [33]:
tensor_two_d = tf.cast(tensor_two_d, tf.float32)

In [34]:
s, u, v = tf.linalg.svd(tensor_two_d)

In [35]:
tensor_three_d = tf.constant(np.random.randint(0, 10, (4,2,3)))
print(tensor_three_d.shape)

x_exp = tf.expand_dims(tensor_three_d, axis=3)
print(x_exp.shape)
print(tf.squeeze(x_exp, axis=3))
print(tf.reshape(x_exp,[4,2,3]))

(4, 2, 3)
(4, 2, 3, 1)
tf.Tensor(
[[[6 8 5]
  [6 7 2]]

 [[4 4 3]
  [5 1 1]]

 [[8 7 1]
  [2 5 8]]

 [[1 0 3]
  [3 8 6]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[6 8 5]
  [6 7 2]]

 [[4 4 3]
  [5 1 1]]

 [[8 7 1]
  [2 5 8]]

 [[1 0 3]
  [3 8 6]]], shape=(4, 2, 3), dtype=int32)


In [36]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis=0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [37]:
x_squeezed = tf.squeeze(x_expanded, axis=0)
for i in range(2):
    x_squeezed = tf.squeeze(x_squeezed, axis=0)

print(x_squeezed)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [38]:
x_reshape = tf.constant([[3, 5, 6, 6],
                         [4, 6, -1, 2]])
tf.reshape(x_reshape, [-1])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2])>

In [39]:
t1 = [[[1,2,3],
      [4,5,6]]]
t2 = [[[7,8,9],
      [10,11,12]]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1, t2], axis=0)

(1, 2, 3)
(1, 2, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [41]:
tf.stack([t1, t2], axis=2)

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]]])>

In [43]:
tf.stack([t1,t2,t1], axis=1)

<tf.Tensor: shape=(1, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6]]]])>

In [46]:
t = tf.constant([[1,2,3],
                [4,5,6]])
paddings =  tf.constant([[0,1],
                       [2,2]])
tf.pad(t, paddings, "CONSTANT", constant_values=0)

<tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])>

In [49]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[1:4]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [54]:
tf.gather(params, [0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [69]:
params = tf.constant([
                    [[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]],
                      
                      [[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]],
                      ])

print(params.shape)
tf.gather(params, [2, 0], axis=1)

(2, 4, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]],

       [[20., 21., 22.],
        [ 0.,  1.,  2.]]], dtype=float32)>

In [76]:
indices = [[2, 1]]
params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [87]:
indices = [[[0, 1], 
           [1, 0]], 

            [[0, 0],
             [1, 1]]]

params = [[['a0', 'b0'], 
           ['c0', 'd0']],

           [['a1', 'b1'], 
            ['c1', 'd1']]]

tf.gather_nd(params, indices, batch_dims=1)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'b0', b'c0'],
       [b'a1', b'd1']], dtype=object)>

In [91]:
tensor_two_d = [
    [1,2,0], 
    [3,],
    [1,5,6,5,6],
    [2,3]
]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [92]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [93]:
tensor_sparse = tf.sparse.SparseTensor(
    indices=[[1,1], [3,4]], values=[11,56], dense_shape=[5,6]
)

In [94]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [96]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]])>

In [97]:
tensor_string = tf.constant(['hello', 'i am', 'a string'])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [100]:
tf.strings.join(tensor_string, separator='+')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am+a string'>

In [101]:
x = tf.constant([1,2])

In [103]:
x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [106]:
x_var.assign_add([5,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0])>

In [113]:
with tf.device('CPU:0'):
    x_1 = tf.constant([1,3,4])
    x_2 = tf.constant([1])

with tf.device('GPU:0'):
    x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
